
STACK=cabal
BUILD_OPTS=--ghc-options -O0 

test: 
	$(STACK) v2-test $(BUILD_OPTS) --test-show-details=always

bin:
	$(STACK) v2-build $(BUILD_OPTS)

clean: 
	$(STACK) v2-clean

distclean: clean 
	rm -rf .stack-work 

ghci:
	$(STACK) repl

turnin: 
	git commit -a -m "turnin"
	git push origin master

upstream:
	git remote add upstream https://github.com/ucsd-cse130/02-random-art.git

update:
	git pull upstream master
